platform :ios, '9.0'
use_frameworks!

target 'Delegate' do

pod 'Alamofire'
pod 'KeychainSwift', '~> 10.0.0'
pod 'FBSDKCoreKit', '~> 4.27.1'
pod 'FBSDKLoginKit', '~> 4.27.1'
pod 'FBSDKShareKit', '~> 4.27.1'
pod 'RxSwift', '~> 4.0.0'
pod 'RxCocoa', '~> 4.0.0'
pod 'RxDataSources', '~> 3.0.2'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'SwiftyJSON', '~> 3.1.4'
pod 'JSQMessagesViewController', '~> 7.3.5'
pod 'FXPageControl', '~> 1.5'
pod 'Cosmos', '~> 12.0.1'
pod 'Branch', '~> 0.20.2'
pod 'TOCropViewController', '~> 2.1.0'
pod 'SwiftMessages'
pod 'PKHUD'
pod 'TwitterKit'
pod 'GoogleSignIn'
pod 'GZIP'
pod 'SDWebImage', '~> 4.2.1'
pod 'AnimatableReload'
pod 'LEMirroredImagePicker', '~> 0.1'
pod 'JVFloatLabeledTextField', '~> 1.2'
pod 'SkyFloatingLabelTextField', '~> 3.4'

end
